### ISSUE TITLE
Support Class Name Language Template

### ISSUE THREAD

**Issue by maykefreitas** [tailwindcss/intellisense#138] opened 2020-06-30 16:06 UTC
Hi.

Is there a way to support class name language templates like this https://github.com/michal-wrzosek/cntl?

Thank you.

**Comment by bradlc** [comment] 2020-06-30 17:37
Hey @maykefreitas, this is a duplicate of #129

**Closed by bradlc** 2020-06-30 17:37 UTC

**Comment by maykefreitas** [comment] 2020-07-02 23:48
Hey @bradlc . Thank you, I'll watch this.
